w = {}


function w.levelGen(lvl)
--This script was originally humanmade; BUT, same as blockDestroyer.lua; it was horribly bad made
-- so i asked gemini to optimize it; i tried; but it didn't work; and as much as im trying to understand
-- arrays; list i can't seem to understand; in the meantime; this would do the trick ;/

block.ubicationSide = {180,240,300,360,420,480,540,180,240,300,360,420,480,540,180,240,300,360,420,480,540,180,240,300,360,420,480,540,180,240,300,360,420,480,540,180,240,300,360,420,480,540,180,240,300,360,420,480,540,180,240,300,360,420,480,540}
block.ubicationTopA = {315,290,265,240,215,190,165,140,0,0,0,0,0,0,265,240,215,265,240,215,265,240,215,265,240,215,265,240,215}
block.ubicationTopB = {325,300,275,250,225,200,175,150,0,0,0,0,0,0,275,250,225,275,250,225,275,250,225,275,250,225,275,250,225}

if creatorTools.status == false then
if lvl == 1 then
  blockTotal = 49
          level.detect = 1
      for i = 1, blockTotal do
        if i >=1 and i <=7 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[1], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[1], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
                if i >=8 and i <=14 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[2], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[2], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 

        end
                        if i >=15 and i <=21 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[3], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[3], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 

        end
                                if i >=22 and i <=28 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[4], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[4], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 

        end
                                  if i >=29 and i <=35 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[5], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[5], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 

        end
                                          if i >=36 and i <=42 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[6], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[6], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 

        end
                                                  if i >=43 and i <=49 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[7], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[7], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 

        end
        end

        lvl = 1001

    end

if lvl == 2 then
  blockTotal = 26       
   level.detect = 2
      for i = 1, blockTotal do
        if i >=1 and i <=7 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[1], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[1], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
            if i >=8 and i <=14 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[7], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[7], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
            end
        
            if i >=15 and i <=17 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[1], block.ubicationTopA[i], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[1], block.ubicationTopB[i], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
            end

            if i >=18 and i <=20 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[3], block.ubicationTopA[i], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[3], block.ubicationTopB[i], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
            end
            if i >=21 and i <=23 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[5], block.ubicationTopA[i], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[5], block.ubicationTopB[i], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
            end
                        if i >=24 and i <=26 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[7], block.ubicationTopA[i], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[7], block.ubicationTopB[i], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
            end
            
        end

 
  lvl = 1002
end
if lvl == 3 then
    blockTotal = 21
    for i = 1, blockTotal do
                if i >=1 and i <=2 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[1], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[1], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
                        if i >=3 and i <=5 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[2], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[2], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
                        if i >=6 and i <=7 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[1], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[1], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
                                if i >=8 and i <=14 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[3], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[3], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
                                        if i >=15 and i <=16 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[5], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[5], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
                                                if i >=17 and i <=19 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[4], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[4], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
                                                        if i >=20 and i <=21 then
        block["hitboxupn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopA[5], 60, 10)
        block["hitboxdownn" .. i] = world:newRectangleCollider(block.ubicationSide[i], block.ubicationTopB[5], 60, 10)
        block["hitboxupn" .. i]:setCollisionClass("blockup")
        block["hitboxupn" .. i]:setType("static") 
        block["hitboxdownn" .. i]:setCollisionClass("blockdown")
        block["hitboxdownn" .. i]:setType("static") 
                _G["blockl" .. i .. "exist"] = true 
        end
    end
    lvl = 1003
    level.detect = 3
end
if lvl == 4 then
    blockTotal = 31
        block.hitboxupn1 = world:newRectangleCollider(180, 140-5,60,10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 140+5,60,10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(240, 140-5,60,10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(240, 140+5,60,10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(300, 140-5,60,10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(300, 140+5,60,10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(360, 140-5,60,10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(360, 140+5,60,10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(420, 140-5,60,10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(420, 140+5,60,10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(480, 140-5,60,10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(480, 140+5,60,10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(540, 140-5,60,10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(540, 140+5,60,10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
 
block.hitboxupn8 = world:newRectangleCollider(240, 165-5,60,10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(240, 165+5,60,10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
 
block.hitboxupn9 = world:newRectangleCollider(300, 190-5,60,10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(300, 190+5,60,10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
 
block.hitboxupn10 = world:newRectangleCollider(360, 215-5,60,10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(360, 215+5,60,10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
 
block.hitboxupn11 = world:newRectangleCollider(420, 240-5,60,10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(420, 240+5,60,10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
 
block.hitboxupn12 = world:newRectangleCollider(480, 265-5,60,10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(480, 265+5,60,10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
 
block.hitboxupn13 = world:newRectangleCollider(540, 290-5,60,10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(540, 290+5,60,10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
 
block.hitboxupn14 = world:newRectangleCollider(480, 290-5,60,10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(480, 290+5,60,10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
 
block.hitboxupn15 = world:newRectangleCollider(420, 290-5,60,10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(420, 290+5,60,10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
 
block.hitboxupn16 = world:newRectangleCollider(360, 265-5,60,10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(360, 265+5,60,10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
 
block.hitboxupn17 = world:newRectangleCollider(360, 290-5,60,10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(360, 290+5,60,10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
 
block.hitboxupn18 = world:newRectangleCollider(300, 290-5,60,10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(300, 290+5,60,10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
 
block.hitboxupn19 = world:newRectangleCollider(240, 290-5,60,10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(240, 290+5,60,10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
 
block.hitboxupn20 = world:newRectangleCollider(180, 290-5,60,10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(180, 290+5,60,10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
 
block.hitboxupn21 = world:newRectangleCollider(240, 265-5,60,10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(240, 265+5,60,10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')
 
block.hitboxupn22 = world:newRectangleCollider(300, 240-5,60,10)
block.hitboxupn22:setCollisionClass('blockup')
block.hitboxupn22:setType('static')
block.hitboxdownn22 = world:newRectangleCollider(300, 240+5,60,10)
block.hitboxdownn22:setCollisionClass('blockdown')
block.hitboxdownn22:setType('static')
 
block.hitboxupn23 = world:newRectangleCollider(420, 190-5,60,10)
block.hitboxupn23:setCollisionClass('blockup')
block.hitboxupn23:setType('static')
block.hitboxdownn23 = world:newRectangleCollider(420, 190+5,60,10)
block.hitboxdownn23:setCollisionClass('blockdown')
block.hitboxdownn23:setType('static')
 
block.hitboxupn24 = world:newRectangleCollider(480, 165-5,60,10)
block.hitboxupn24:setCollisionClass('blockup')
block.hitboxupn24:setType('static')
block.hitboxdownn24 = world:newRectangleCollider(480, 165+5,60,10)
block.hitboxdownn24:setCollisionClass('blockdown')
block.hitboxdownn24:setType('static')
 
block.hitboxupn25 = world:newRectangleCollider(480, 215-5,60,10)
block.hitboxupn25:setCollisionClass('blockup')
block.hitboxupn25:setType('static')
block.hitboxdownn25 = world:newRectangleCollider(480, 215+5,60,10)
block.hitboxdownn25:setCollisionClass('blockdown')
block.hitboxdownn25:setType('static')
 
block.hitboxupn26 = world:newRectangleCollider(540, 240-5,60,10)
block.hitboxupn26:setCollisionClass('blockup')
block.hitboxupn26:setType('static')
block.hitboxdownn26 = world:newRectangleCollider(540, 240+5,60,10)
block.hitboxdownn26:setCollisionClass('blockdown')
block.hitboxdownn26:setType('static')
 
block.hitboxupn27 = world:newRectangleCollider(540, 190-5,60,10)
block.hitboxupn27:setCollisionClass('blockup')
block.hitboxupn27:setType('static')
block.hitboxdownn27 = world:newRectangleCollider(540, 190+5,60,10)
block.hitboxdownn27:setCollisionClass('blockdown')
block.hitboxdownn27:setType('static')
 
block.hitboxupn28 = world:newRectangleCollider(180, 240-5,60,10)
block.hitboxupn28:setCollisionClass('blockup')
block.hitboxupn28:setType('static')
block.hitboxdownn28 = world:newRectangleCollider(180, 240+5,60,10)
block.hitboxdownn28:setCollisionClass('blockdown')
block.hitboxdownn28:setType('static')
 
block.hitboxupn29 = world:newRectangleCollider(240, 215-5,60,10)
block.hitboxupn29:setCollisionClass('blockup')
block.hitboxupn29:setType('static')
block.hitboxdownn29 = world:newRectangleCollider(240, 215+5,60,10)
block.hitboxdownn29:setCollisionClass('blockdown')
block.hitboxdownn29:setType('static')
block.hitboxupn30 = world:newRectangleCollider(180, 190-5,60,10)
block.hitboxupn30:setCollisionClass('blockup')
block.hitboxupn30:setType('static')
block.hitboxdownn30 = world:newRectangleCollider(180, 190+5,60,10)
block.hitboxdownn30:setCollisionClass('blockdown')
block.hitboxdownn30:setType('static')
block.hitboxupn31 = world:newRectangleCollider(360, 165-5,60,10)
block.hitboxupn31:setCollisionClass('blockup')
block.hitboxupn31:setType('static')
block.hitboxdownn31 = world:newRectangleCollider(360, 165+5,60,10)
block.hitboxdownn31:setCollisionClass('blockdown')
block.hitboxdownn31:setType('static')
for i =1, blockTotal do
  _G["blockl" .. i .. "exist"] = true 
end
    lvl = 1004
    level.detect = 4
end
end
if lvl == 5 then
    blockTotal = 20
block.hitboxupn1 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(300, 165-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(300, 165+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(300, 190-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(300, 190+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(300, 215-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(300, 215+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(300, 240-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(300, 240+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(300, 265-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(300, 265+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(420, 265-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(420, 265+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(420, 240-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(420, 240+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(420, 215-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(420, 215+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(420, 165-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(420, 165+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(420, 190-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(420, 190+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(240, 215-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(240, 215+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(480, 215-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(480, 215+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(540, 290-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(540, 290+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(540, 140-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(540, 140+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(180, 215-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(180, 215+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(540, 215-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(540, 215+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(360, 290-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(360, 290+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(360, 140-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(360, 140+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
for i =1, blockTotal do
  _G["blockl" .. i .. "exist"] = true 
end
    lvl = 1005
    level.detect = 5
end
if lvl == 6 then
    blockTotal = 25
block.hitboxupn1 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(180, 165-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(180, 165+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(180, 190-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(180, 190+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(180, 215-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(180, 215+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(180, 240-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(180, 240+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(180, 265-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(180, 265+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(240, 290-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(240, 290+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(540, 290-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(540, 290+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(540, 265-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(540, 265+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(540, 240-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(540, 240+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(540, 215-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(540, 215+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(540, 190-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(540, 190+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(540, 165-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(540, 165+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(540, 140-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(540, 140+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(480, 140-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(480, 140+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(420, 165-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(420, 165+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(420, 190-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(420, 190+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(300, 265-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(300, 265+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(300, 240-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(300, 240+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
block.hitboxupn21 = world:newRectangleCollider(300, 140-5, 60, 10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(300, 140+5, 60, 10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')
block.hitboxupn22 = world:newRectangleCollider(420, 290-5, 60, 10)
block.hitboxupn22:setCollisionClass('blockup')
block.hitboxupn22:setType('static')
block.hitboxdownn22 = world:newRectangleCollider(420, 290+5, 60, 10)
block.hitboxdownn22:setCollisionClass('blockdown')
block.hitboxdownn22:setType('static')
block.hitboxupn23 = world:newRectangleCollider(360, 215-5, 60, 10)
block.hitboxupn23:setCollisionClass('blockup')
block.hitboxupn23:setType('static')
block.hitboxdownn23 = world:newRectangleCollider(360, 215+5, 60, 10)
block.hitboxdownn23:setCollisionClass('blockdown')
block.hitboxdownn23:setType('static')
block.hitboxupn24 = world:newRectangleCollider(240, 165-5, 60, 10)
block.hitboxupn24:setCollisionClass('blockup')
block.hitboxupn24:setType('static')
block.hitboxdownn24 = world:newRectangleCollider(240, 165+5, 60, 10)
block.hitboxdownn24:setCollisionClass('blockdown')
block.hitboxdownn24:setType('static')
block.hitboxupn25 = world:newRectangleCollider(480, 265-5, 60, 10)
block.hitboxupn25:setCollisionClass('blockup')
block.hitboxupn25:setType('static')
block.hitboxdownn25 = world:newRectangleCollider(480, 265+5, 60, 10)
block.hitboxdownn25:setCollisionClass('blockdown')
block.hitboxdownn25:setType('static')
for i =1, blockTotal do
  _G["blockl" .. i .. "exist"] = true 
end
    lvl = 1006
    level.detect = 6
end
if lvl == 7 then
    blockTotal = 23
block.hitboxupn1 = world:newRectangleCollider(180, 240-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 240+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(540, 240-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(540, 240+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(300, 190-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(300, 190+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(300, 290-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(300, 290+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(420, 190-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(420, 190+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(420, 290-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(420, 290+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(540, 140-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(540, 140+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(540, 290-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(540, 290+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(180, 190-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(180, 190+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(540, 190-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(540, 190+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(240, 240-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(240, 240+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(300, 240-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(300, 240+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(360, 240-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(360, 240+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(420, 240-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(420, 240+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(480, 240-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(480, 240+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(480, 265-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(480, 265+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(360, 265-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(360, 265+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(240, 265-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(240, 265+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
block.hitboxupn21 = world:newRectangleCollider(180, 165-5, 60, 10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(180, 165+5, 60, 10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')
block.hitboxupn22 = world:newRectangleCollider(360, 165-5, 60, 10)
block.hitboxupn22:setCollisionClass('blockup')
block.hitboxupn22:setType('static')
block.hitboxdownn22 = world:newRectangleCollider(360, 165+5, 60, 10)
block.hitboxdownn22:setCollisionClass('blockdown')
block.hitboxdownn22:setType('static')
block.hitboxupn23 = world:newRectangleCollider(540, 165-5, 60, 10)
block.hitboxupn23:setCollisionClass('blockup')
block.hitboxupn23:setType('static')
block.hitboxdownn23 = world:newRectangleCollider(540, 165+5, 60, 10)
block.hitboxdownn23:setCollisionClass('blockdown')
block.hitboxdownn23:setType('static')
for i =1, blockTotal do
  _G["blockl" .. i .. "exist"] = true 
end
    lvl = 1007
    level.detect = 7
end
if lvl == 8 then
    blockTotal = 24
block.hitboxupn1 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(300, 265-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(300, 265+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(540, 290-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(540, 290+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(420, 240-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(420, 240+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(420, 265-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(420, 265+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(300, 240-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(300, 240+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(240, 240-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(240, 240+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(300, 215-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(300, 215+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(300, 190-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(300, 190+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(240, 190-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(240, 190+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(300, 165-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(300, 165+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(360, 240-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(360, 240+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(360, 190-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(360, 190+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(420, 190-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(420, 190+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(420, 215-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(420, 215+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(420, 165-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(420, 165+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(480, 190-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(480, 190+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(480, 240-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(480, 240+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(540, 140-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(540, 140+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
block.hitboxupn21 = world:newRectangleCollider(300, 290-5, 60, 10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(300, 290+5, 60, 10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')
block.hitboxupn22 = world:newRectangleCollider(420, 290-5, 60, 10)
block.hitboxupn22:setCollisionClass('blockup')
block.hitboxupn22:setType('static')
block.hitboxdownn22 = world:newRectangleCollider(420, 290+5, 60, 10)
block.hitboxdownn22:setCollisionClass('blockdown')
block.hitboxdownn22:setType('static')
block.hitboxupn23 = world:newRectangleCollider(300, 140-5, 60, 10)
block.hitboxupn23:setCollisionClass('blockup')
block.hitboxupn23:setType('static')
block.hitboxdownn23 = world:newRectangleCollider(300, 140+5, 60, 10)
block.hitboxdownn23:setCollisionClass('blockdown')
block.hitboxdownn23:setType('static')
block.hitboxupn24 = world:newRectangleCollider(420, 140-5, 60, 10)
block.hitboxupn24:setCollisionClass('blockup')
block.hitboxupn24:setType('static')
block.hitboxdownn24 = world:newRectangleCollider(420, 140+5, 60, 10)
block.hitboxdownn24:setCollisionClass('blockdown')
block.hitboxdownn24:setType('static')

for i =1, blockTotal do
  _G["blockl" .. i .. "exist"] = true 
end
    lvl = 1008
    level.detect = 8
end
if lvl == 9 then
    blockTotal = 22
block.hitboxupn1 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(240, 140-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(240, 140+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(240, 165-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(240, 165+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(300, 190-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(300, 190+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(300, 215-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(300, 215+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(360, 240-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(360, 240+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(360, 265-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(360, 265+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(360, 290-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(360, 290+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(420, 215-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(420, 215+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(420, 190-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(420, 190+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(480, 165-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(480, 165+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(480, 140-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(480, 140+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(540, 140-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(540, 140+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(180, 265-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(180, 265+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(240, 290-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(240, 290+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(540, 290-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(540, 290+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(480, 290-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(480, 290+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(540, 265-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(540, 265+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(300, 140-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(300, 140+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
block.hitboxupn21 = world:newRectangleCollider(360, 140-5, 60, 10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(360, 140+5, 60, 10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')
block.hitboxupn22 = world:newRectangleCollider(420, 140-5, 60, 10)
block.hitboxupn22:setCollisionClass('blockup')
block.hitboxupn22:setType('static')
block.hitboxdownn22 = world:newRectangleCollider(420, 140+5, 60, 10)
block.hitboxdownn22:setCollisionClass('blockdown')
block.hitboxdownn22:setType('static')

for i =1, blockTotal do
  _G["blockl" .. i .. "exist"] = true 
end
    lvl = 1009
    level.detect = 9
end
if lvl == 10 then
    blockTotal = 18
block.hitboxupn1 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(240, 165-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(240, 165+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(180, 190-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(180, 190+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(240, 265-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(240, 265+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(180, 240-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(180, 240+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(540, 290-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(540, 290+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(480, 265-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(480, 265+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(540, 240-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(540, 240+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(540, 140-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(540, 140+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(480, 165-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(480, 165+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(540, 190-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(540, 190+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(300, 240-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(300, 240+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(360, 240-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(360, 240+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(420, 240-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(420, 240+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(300, 190-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(300, 190+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(360, 190-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(360, 190+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(420, 190-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(420, 190+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')

for i =1, blockTotal do
  _G["blockl" .. i .. "exist"] = true 
end
    lvl = 1010
    level.detect = 10
end

if lvl == 11 then 
 blockTotal = 21
block.hitboxupn1 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(240, 265-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(240, 265+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(240, 240-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(240, 240+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(300, 215-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(300, 215+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(360, 190-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(360, 190+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(360, 165-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(360, 165+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(420, 140-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(420, 140+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(180, 215-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(180, 215+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(240, 190-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(240, 190+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(240, 165-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(240, 165+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(300, 140-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(300, 140+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(360, 290-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(360, 290+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(420, 265-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(420, 265+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(420, 240-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(420, 240+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(480, 215-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(480, 215+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(540, 190-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(540, 190+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(540, 165-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(540, 165+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(480, 290-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(480, 290+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(540, 265-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(540, 265+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
block.hitboxupn21 = world:newRectangleCollider(540, 240-5, 60, 10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(540, 240+5, 60, 10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')

                    

 for i =1, blockTotal do 
 _G["blockl" .. i .. "exist"] = true 
 end
  lvl = 1011
  level.detect = 11
end

if lvl == 12 then 
blockTotal = 27
    block.hitboxupn1 = world:newRectangleCollider(360, 140-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(360, 140+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(360, 165-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(360, 165+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(360, 190-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(360, 190+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(360, 215-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(360, 215+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(360, 240-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(360, 240+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(360, 265-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(360, 265+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(360, 290-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(360, 290+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(420, 190-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(420, 190+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(300, 190-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(300, 190+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(240, 215-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(240, 215+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(180, 240-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(180, 240+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(480, 215-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(480, 215+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(540, 240-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(540, 240+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(540, 165-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(540, 165+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(180, 165-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(180, 165+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(240, 140-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(240, 140+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(300, 140-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(300, 140+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(420, 140-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(420, 140+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(480, 140-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(480, 140+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(180, 265-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(180, 265+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
block.hitboxupn21 = world:newRectangleCollider(240, 265-5, 60, 10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(240, 265+5, 60, 10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')
block.hitboxupn22 = world:newRectangleCollider(300, 265-5, 60, 10)
block.hitboxupn22:setCollisionClass('blockup')
block.hitboxupn22:setType('static')
block.hitboxdownn22 = world:newRectangleCollider(300, 265+5, 60, 10)
block.hitboxdownn22:setCollisionClass('blockdown')
block.hitboxdownn22:setType('static')
block.hitboxupn23 = world:newRectangleCollider(420, 265-5, 60, 10)
block.hitboxupn23:setCollisionClass('blockup')
block.hitboxupn23:setType('static')
block.hitboxdownn23 = world:newRectangleCollider(420, 265+5, 60, 10)
block.hitboxdownn23:setCollisionClass('blockdown')
block.hitboxdownn23:setType('static')
block.hitboxupn24 = world:newRectangleCollider(480, 265-5, 60, 10)
block.hitboxupn24:setCollisionClass('blockup')
block.hitboxupn24:setType('static')
block.hitboxdownn24 = world:newRectangleCollider(480, 265+5, 60, 10)
block.hitboxdownn24:setCollisionClass('blockdown')
block.hitboxdownn24:setType('static')
block.hitboxupn25 = world:newRectangleCollider(540, 265-5, 60, 10)
block.hitboxupn25:setCollisionClass('blockup')
block.hitboxupn25:setType('static')
block.hitboxdownn25 = world:newRectangleCollider(540, 265+5, 60, 10)
block.hitboxdownn25:setCollisionClass('blockdown')
block.hitboxdownn25:setType('static')
block.hitboxupn26 = world:newRectangleCollider(240, 290-5, 60, 10)
block.hitboxupn26:setCollisionClass('blockup')
block.hitboxupn26:setType('static')
block.hitboxdownn26 = world:newRectangleCollider(240, 290+5, 60, 10)
block.hitboxdownn26:setCollisionClass('blockdown')
block.hitboxdownn26:setType('static')
block.hitboxupn27 = world:newRectangleCollider(480, 290-5, 60, 10)
block.hitboxupn27:setCollisionClass('blockup')
block.hitboxupn27:setType('static')
block.hitboxdownn27 = world:newRectangleCollider(480, 290+5, 60, 10)
block.hitboxdownn27:setCollisionClass('blockdown')
block.hitboxdownn27:setType('static')
     

for i =1, blockTotal do 
_G["blockl" .. i .. "exist"] = true 
end
   lvl = 1012 
   level.detect = 12 
end

if lvl == 13 then 
 blockTotal = 26
block.hitboxupn1 = world:newRectangleCollider(180, 140-5, 60, 10)
block.hitboxupn1:setCollisionClass('blockup')
block.hitboxupn1:setType('static')
block.hitboxdownn1 = world:newRectangleCollider(180, 140+5, 60, 10)
block.hitboxdownn1:setCollisionClass('blockdown')
block.hitboxdownn1:setType('static')
block.hitboxupn2 = world:newRectangleCollider(180, 165-5, 60, 10)
block.hitboxupn2:setCollisionClass('blockup')
block.hitboxupn2:setType('static')
block.hitboxdownn2 = world:newRectangleCollider(180, 165+5, 60, 10)
block.hitboxdownn2:setCollisionClass('blockdown')
block.hitboxdownn2:setType('static')
block.hitboxupn3 = world:newRectangleCollider(180, 190-5, 60, 10)
block.hitboxupn3:setCollisionClass('blockup')
block.hitboxupn3:setType('static')
block.hitboxdownn3 = world:newRectangleCollider(180, 190+5, 60, 10)
block.hitboxdownn3:setCollisionClass('blockdown')
block.hitboxdownn3:setType('static')
block.hitboxupn4 = world:newRectangleCollider(180, 215-5, 60, 10)
block.hitboxupn4:setCollisionClass('blockup')
block.hitboxupn4:setType('static')
block.hitboxdownn4 = world:newRectangleCollider(180, 215+5, 60, 10)
block.hitboxdownn4:setCollisionClass('blockdown')
block.hitboxdownn4:setType('static')
block.hitboxupn5 = world:newRectangleCollider(180, 240-5, 60, 10)
block.hitboxupn5:setCollisionClass('blockup')
block.hitboxupn5:setType('static')
block.hitboxdownn5 = world:newRectangleCollider(180, 240+5, 60, 10)
block.hitboxdownn5:setCollisionClass('blockdown')
block.hitboxdownn5:setType('static')
block.hitboxupn6 = world:newRectangleCollider(180, 265-5, 60, 10)
block.hitboxupn6:setCollisionClass('blockup')
block.hitboxupn6:setType('static')
block.hitboxdownn6 = world:newRectangleCollider(180, 265+5, 60, 10)
block.hitboxdownn6:setCollisionClass('blockdown')
block.hitboxdownn6:setType('static')
block.hitboxupn7 = world:newRectangleCollider(180, 290-5, 60, 10)
block.hitboxupn7:setCollisionClass('blockup')
block.hitboxupn7:setType('static')
block.hitboxdownn7 = world:newRectangleCollider(180, 290+5, 60, 10)
block.hitboxdownn7:setCollisionClass('blockdown')
block.hitboxdownn7:setType('static')
block.hitboxupn8 = world:newRectangleCollider(240, 290-5, 60, 10)
block.hitboxupn8:setCollisionClass('blockup')
block.hitboxupn8:setType('static')
block.hitboxdownn8 = world:newRectangleCollider(240, 290+5, 60, 10)
block.hitboxdownn8:setCollisionClass('blockdown')
block.hitboxdownn8:setType('static')
block.hitboxupn9 = world:newRectangleCollider(300, 290-5, 60, 10)
block.hitboxupn9:setCollisionClass('blockup')
block.hitboxupn9:setType('static')
block.hitboxdownn9 = world:newRectangleCollider(300, 290+5, 60, 10)
block.hitboxdownn9:setCollisionClass('blockdown')
block.hitboxdownn9:setType('static')
block.hitboxupn10 = world:newRectangleCollider(300, 265-5, 60, 10)
block.hitboxupn10:setCollisionClass('blockup')
block.hitboxupn10:setType('static')
block.hitboxdownn10 = world:newRectangleCollider(300, 265+5, 60, 10)
block.hitboxdownn10:setCollisionClass('blockdown')
block.hitboxdownn10:setType('static')
block.hitboxupn11 = world:newRectangleCollider(300, 240-5, 60, 10)
block.hitboxupn11:setCollisionClass('blockup')
block.hitboxupn11:setType('static')
block.hitboxdownn11 = world:newRectangleCollider(300, 240+5, 60, 10)
block.hitboxdownn11:setCollisionClass('blockdown')
block.hitboxdownn11:setType('static')
block.hitboxupn12 = world:newRectangleCollider(300, 215-5, 60, 10)
block.hitboxupn12:setCollisionClass('blockup')
block.hitboxupn12:setType('static')
block.hitboxdownn12 = world:newRectangleCollider(300, 215+5, 60, 10)
block.hitboxdownn12:setCollisionClass('blockdown')
block.hitboxdownn12:setType('static')
block.hitboxupn13 = world:newRectangleCollider(360, 215-5, 60, 10)
block.hitboxupn13:setCollisionClass('blockup')
block.hitboxupn13:setType('static')
block.hitboxdownn13 = world:newRectangleCollider(360, 215+5, 60, 10)
block.hitboxdownn13:setCollisionClass('blockdown')
block.hitboxdownn13:setType('static')
block.hitboxupn14 = world:newRectangleCollider(420, 215-5, 60, 10)
block.hitboxupn14:setCollisionClass('blockup')
block.hitboxupn14:setType('static')
block.hitboxdownn14 = world:newRectangleCollider(420, 215+5, 60, 10)
block.hitboxdownn14:setCollisionClass('blockdown')
block.hitboxdownn14:setType('static')
block.hitboxupn15 = world:newRectangleCollider(420, 240-5, 60, 10)
block.hitboxupn15:setCollisionClass('blockup')
block.hitboxupn15:setType('static')
block.hitboxdownn15 = world:newRectangleCollider(420, 240+5, 60, 10)
block.hitboxdownn15:setCollisionClass('blockdown')
block.hitboxdownn15:setType('static')
block.hitboxupn16 = world:newRectangleCollider(420, 265-5, 60, 10)
block.hitboxupn16:setCollisionClass('blockup')
block.hitboxupn16:setType('static')
block.hitboxdownn16 = world:newRectangleCollider(420, 265+5, 60, 10)
block.hitboxdownn16:setCollisionClass('blockdown')
block.hitboxdownn16:setType('static')
block.hitboxupn17 = world:newRectangleCollider(420, 290-5, 60, 10)
block.hitboxupn17:setCollisionClass('blockup')
block.hitboxupn17:setType('static')
block.hitboxdownn17 = world:newRectangleCollider(420, 290+5, 60, 10)
block.hitboxdownn17:setCollisionClass('blockdown')
block.hitboxdownn17:setType('static')
block.hitboxupn18 = world:newRectangleCollider(360, 290-5, 60, 10)
block.hitboxupn18:setCollisionClass('blockup')
block.hitboxupn18:setType('static')
block.hitboxdownn18 = world:newRectangleCollider(360, 290+5, 60, 10)
block.hitboxdownn18:setCollisionClass('blockdown')
block.hitboxdownn18:setType('static')
block.hitboxupn19 = world:newRectangleCollider(480, 290-5, 60, 10)
block.hitboxupn19:setCollisionClass('blockup')
block.hitboxupn19:setType('static')
block.hitboxdownn19 = world:newRectangleCollider(480, 290+5, 60, 10)
block.hitboxdownn19:setCollisionClass('blockdown')
block.hitboxdownn19:setType('static')
block.hitboxupn20 = world:newRectangleCollider(480, 265-5, 60, 10)
block.hitboxupn20:setCollisionClass('blockup')
block.hitboxupn20:setType('static')
block.hitboxdownn20 = world:newRectangleCollider(480, 265+5, 60, 10)
block.hitboxdownn20:setCollisionClass('blockdown')
block.hitboxdownn20:setType('static')
block.hitboxupn21 = world:newRectangleCollider(480, 240-5, 60, 10)
block.hitboxupn21:setCollisionClass('blockup')
block.hitboxupn21:setType('static')
block.hitboxdownn21 = world:newRectangleCollider(480, 240+5, 60, 10)
block.hitboxdownn21:setCollisionClass('blockdown')
block.hitboxdownn21:setType('static')
block.hitboxupn22 = world:newRectangleCollider(480, 215-5, 60, 10)
block.hitboxupn22:setCollisionClass('blockup')
block.hitboxupn22:setType('static')
block.hitboxdownn22 = world:newRectangleCollider(480, 215+5, 60, 10)
block.hitboxdownn22:setCollisionClass('blockdown')
block.hitboxdownn22:setType('static')
block.hitboxupn23 = world:newRectangleCollider(480, 190-5, 60, 10)
block.hitboxupn23:setCollisionClass('blockup')
block.hitboxupn23:setType('static')
block.hitboxdownn23 = world:newRectangleCollider(480, 190+5, 60, 10)
block.hitboxdownn23:setCollisionClass('blockdown')
block.hitboxdownn23:setType('static')
block.hitboxupn24 = world:newRectangleCollider(480, 165-5, 60, 10)
block.hitboxupn24:setCollisionClass('blockup')
block.hitboxupn24:setType('static')
block.hitboxdownn24 = world:newRectangleCollider(480, 165+5, 60, 10)
block.hitboxdownn24:setCollisionClass('blockdown')
block.hitboxdownn24:setType('static')
block.hitboxupn25 = world:newRectangleCollider(480, 140-5, 60, 10)
block.hitboxupn25:setCollisionClass('blockup')
block.hitboxupn25:setType('static')
block.hitboxdownn25 = world:newRectangleCollider(480, 140+5, 60, 10)
block.hitboxdownn25:setCollisionClass('blockdown')
block.hitboxdownn25:setType('static')
block.hitboxupn26 = world:newRectangleCollider(540, 290-5, 60, 10)
block.hitboxupn26:setCollisionClass('blockup')
block.hitboxupn26:setType('static')
block.hitboxdownn26 = world:newRectangleCollider(540, 290+5, 60, 10)
block.hitboxdownn26:setCollisionClass('blockdown')
block.hitboxdownn26:setType('static') 

for i =1, blockTotal do 
_G["blockl" .. i .. "exist"] = true 
end
lvl = 1013
  level.detect = 13
end

end

return w


-- if lvl == ¿? then --to make a level; first set its number
--  blockTotal = ¿? -- then define how many blocks does it have
                    --then copy-paste the console output of the level maker

-- for i =1, blockTotal do --last, leave this as is; this allows for the blocks to be broken
-- _G["blockl" .. i .. "exist"] = true 
-- end
 --   lvl = 10¿? -- and define the raw value of the level
 --   level.detect = ¿? -- and the detection of the current level
-- end





